server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:    host: smtp.gmail.com
    port: 587
    username: teamproject85123@gmail.com
    password: xlavmfhwprxm0
    properties:      mail:
        smtp:
          starttls:
          enable: true
          required: true
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
      
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/rc341mq9bm8s59xz?serverTimezone=Asia/Seoul
#    username: ty4gx9k71np10knq
#    password: u8nrjdq4586a8snk

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/velog?serverTimezone=Asia/Seoul
    username: root
    password: toor

  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: -6hre9mgcrflbs3omcmrrj99ifac7aaog.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 420686082979362
            client-secret: 0f39e944d9239eb447942e72f3b3f499
            scope:
            - public_profile
            - email
          naver:
            client-id: CTtIhr9aeX0EvA0b1jCr
            client-secret: DneyaS0HDy
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json형태로 가지고 올때 response라는 key값으로 데이터를 전달해 준다

mybatis:
  mapper-locations:  - /mappers/*xml