server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamproject85123@gmail.com
    password: xlavmfhwprxm0
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mariadb://localhost:3306/velog-aiden?serverTimezone=Asia/Seoul
    username: root
    password: toor
=======
    url: jdbc:mariadb://dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/rc341mq9bm8s59xz?serverTimezone=Asia/Seoul
    username: ty4gx9k71np10knq
<<<<<<< HEAD
    password: eg8ddneeashg6unls
=======
    password: tuhyvjphw4siv92j
<<<<<<< HEAD


mybatis:
  mapper-locations:
  - /mappers/*xml